import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./components/layout";

export const metadata = {
  title: "The title appears on the top",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}  {/*라우팅으로 결정된 현재 페이지가 랜더링되는 자리: <Layout>태그 사이 10:51*/}
        </Layout>
      </body>
    </html>
  );
}
