#250610 10:58 AM application.properties? .yml??? ??
spring:
  servlet:
    multipart:
      location: D:\lecture\10_spring-webmvc\chap06-file-upload
      max-file-size: 10MB
      max-request-size: 10MB
#yml?? ??? **???? ??? ??**?? ?? ? ?